
CREATE DATABASE IF NOT EXISTS `dweb`;
USE `dweb`;

CREATE TABLE IF NOT EXISTS `tickets` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `TNAME` varchar(50) DEFAULT NULL,
  `CURP` varchar(50) DEFAULT NULL,
  `NAME` varchar(50) DEFAULT NULL,
  `LPNAME` varchar(50) DEFAULT NULL,
  `LMNAME` varchar(50) DEFAULT NULL,
  `TELEPHONE` varchar(10) DEFAULT NULL,
  `CELPHONE` varchar(10) DEFAULT NULL,
  `MAIL` varchar(50) DEFAULT NULL,
  `LEVEL` varchar(50) DEFAULT NULL,
  `CITY` varchar(50) DEFAULT NULL,
  `SUBJECT` varchar(50) DEFAULT NULL,

  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
